on:
  - push
  - workflow_dispatch

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/latex-action
      - name: Build document
        shell: bash
        run: |
          echo "$PATH"
