on:
  - push
  - workflow_dispatch

jobs:
  build-doc:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare TeXLive
        shell: bash
        run: exec bash .github/workflows/get-tl.sh
      - name: Build document
        shell: bash
        run: |
          echo "$PATH"
